# name: Playwright Automation Tests

# # Trigger workflow on push or pull requests to main/master branches
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]

# jobs:
#   test:
#     name: Run Playwright Tests
#     timeout-minutes: 60
#     runs-on: windows-latest

#     steps:
#     - name: Check out repository
#       uses: actions/checkout@v4

#     - name: Set up Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#         cache: 'npm'
               
#     - name: Install dependencies
#       run: npm ci
      
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps

#     - name: Run Playwright tests
#       run: npx cross-env ENV=test cucumber-js --tags="@Regression" --exit
#       env:
#         CI: true # Set CI environment variable for better test stability

#     - name: Upload test results
#       uses: actions/upload-artifact@v4
#       if: always() # Always upload test results, even if tests fail
#       with:
#         name: playwright-report
#         path: playwright-report
#         retention-days: 30

name: Playwright Automation Tests

# Trigger workflow on push or pull requests to main/master branches
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Playwright Tests
    timeout-minutes: 60
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
               
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Install report generation dependencies
      run: npm install cross-env cucumber-html-reporter --no-save
      
    - name: Run Cucumber tests with Playwright
      run: npx cross-env ENV=test cucumber-js --tags="@Regression" --exit --format json:cucumber-report.json
      env:
        CI: true
      continue-on-error: true  # Continue workflow even if tests fail

    - name: Generate HTML report from Cucumber JSON
      if: always()
      run: npx cucumber-html-reporter --json cucumber-report.json --output cucumber-report.html
      continue-on-error: true  # Continue even if report generation fails

    - name: Upload Cucumber reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-reports
        path: |
          cucumber-report.json
          cucumber-report.html
        retention-days: 30
        
    - name: Upload Playwright traces
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: test-results/
        retention-days: 30